application: fieldsensing
version: 1
runtime: go
api_version: 2

handlers:

- url: /html
  static_dir: static/html

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /(.*\.(gif|png|jpg))
  static_files: static/images/\1
  upload: static/(.*\.(gif|png|jpg))

- url: /.*
  script: _go_app
  login: required


# Files for appengine to ignore:

skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?.git/.*$
  - ^venv/.*$
  - ^(.*/)?/google_appengine/.*